### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by AnitaMigueles** [alegon23/mercadoLiebre#2]
1. **Cumple**, el sitio cuenta con todos los elementos.
2. **Cumple** con ambos puntos.
3. **Cumple**.
4. **Cumple**.
5. **Cumple**.
6. **Cumple**.
7. **Cumple**.
8. **Cumple**.
9. Me gustó el detalle de aplicarle también una transición al botón borrar del formulario de registro de usuarios.
10. Creo que podrían mejorarse:
-  los puntos de corte para las media queries, ya que no son los solicitados.
- la apariencia de la barra de búsqueda para tablets y computadoras. En la imágen dada, la barra y la lupita estaban separados y ambos tenían el borde negro.

**Comment by alegon23** [comment]
Muchas gracias por las devoluciones Ana! 🤗
Con respecto al punto 10, tomé esas decisiones de diseño para que el sitio se vea mejor en general:
- Agregué media queries para tener un mayor control de la adaptación de la página
- La barra de búsqueda me guié de uno de los diseños que aparecía como captura de pantalla en las consignas
